version: '3.9'
services:
  app:
    container_name: 'siege_td_backend'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
    networks:
      - siege_td_backend
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
      - '${WS_PORT}:${WS_PORT}'
    env_file:
      - '.env'

networks:
  siege_td_backend: